# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Women Techmakers Istanbul 2015"
email: "wtm@gdgistanbul.com"
description: "Women Techmakers is a set of event about Women in technology"
baseurl: ""
url: "http://wtmistanbul.com/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-58630743-1"
googleAnalyticsSiteUrl: "wtmistanbul.com"
siteVerification: "J78BVBOHc0PWM6qbrydtmvG1KjsM5HFF4JUSzcuoqCw"

# Organizer Info
organizerName: "GDG Women Istanbul"
organizerAlternateName: "Google Developer Group Istanbul"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "wtm@gdgistanbul.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.gdgistanbul.com/"

# Head
metaKeywords: "wtm, women, womentechmakers, event, gdg, google, programming, android, chrome, developers, Istanbul"
twitterAccount: "@wtmistanbul"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/16AI23TnSQFg5yCqOIXeCj1hSlQvw1ihtx0XenZKfflk/viewform?usp=send_form"
c4sponsorsUrl: "https://docs.google.com/a/gdgistanbul.com/file/d/0B5Ewb5NwqbwIY0tvVTl2U2VjZkU/edit?usp=drive_web"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Ana Sayfa"}
 # - {permalink: "/blog/", text: "Blog"}
 #- {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Konuşmacılar"}
 - {permalink: "/#partners", text: "Sponsorlar"}
 #- {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Ulaşım"}
 - {permalink: "/startup/", text: "Startup Launch"}
 - {permalink: "http://wtm14.devfesttr.com/", text: "DevFestW'14"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/16AI23TnSQFg5yCqOIXeCj1hSlQvw1ihtx0XenZKfflk/viewform?usp=send_form", text: "Konuşmacı Ol"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/16AI23TnSQFg5yCqOIXeCj1hSlQvw1ihtx0XenZKfflk/viewform?usp=send_form", text: "Konuşmacı Ol"}
 - {link: "https://docs.google.com/a/gdgistanbul.com/file/d/0B5Ewb5NwqbwIY0tvVTl2U2VjZkU/edit?usp=drive_web", text: "Sponsor Ol"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "WTM Istanbul 2015"
eventDate: "15 March, 2015"
typeoutTextValues: '"Women", "Techmakers", "Istanbul"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://docs.google.com/forms/d/16AI23TnSQFg5yCqOIXeCj1hSlQvw1ihtx0XenZKfflk/viewform?usp=send_form", text: "Konuşmacı Ol"}
 - {permalink: "/#tickets", text: "Kayıt Ol"}

# About Block
aboutTitle: "Women Techmakers Hakkında"
aboutBlock:
 - {title: "Dünya Kadınlar Günü", image: "conference.jpg", text: "Mart ayında dünya kadınlar gününü kutlarken teknoloji bilişim ve mühendislik alanında kadınları destekliyor ve ilham veriyoruz." }
 - {title: "Teknoloji", image: "workshop.jpg", text: "Teknoloji sektörundeki gelişmeler, yenilikler ve haberleri dinlemek icin sahneye teknoloji dunyasında calışan başarılı kadınları davet ediyoruz." }
 - {title: "Startup Launch", image: "hackathon.jpg", text: "Kadın girişimciliği destekliyoruz. Girişimciler ve girşimci adayları, WTM İstanbul'da yatırımcılarla bir araya geliyor!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "700", specialCharacter: "+", info: "katılımcı", detail: "kadın ve erkek"}
 - {count: "52", specialCharacter: "+", info: "konuşmacı", detail: "1 Google çalışanı haricinde hepsi kadın"}
 - {count: "4", specialCharacter: "", info: "paralel oturum", detail: "ve çalıştaylar"}

# Latest News Block
latestNewsTitle: "Son haberler"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Rockstar konuşmacılar"
rockstarSpeakersButtonText: "Tüm konuşmacılar"

# Location Block
locationBlockTitle: "Ulaşım"
eventLocationName: "Bahcesehir Üniversitesi Besiktas Kampüsü"
eventLocationLink: "http://maps.google.com/maps?ll=41.041994,29.009049&z=16&t=m&hl=en-US&gl=US&mapclient=embed&cid=8534833363515311385"
eventStreetAddress: "Ciragan Caddesi, Besiktas"
eventAddressLocality: "Istanbul"
eventAddressLocalityRegion: ""
eventPostalCode: ""
eventAddressCountry: "Türkiye"
eventStartTime: "2015-03-15T09:00"
eventDoorTime: "09:00"
eventEndTime: "2015-03-15T17:30"
eventPlaceCoordinates: "41.041994, 29.009049"
mapCenterCoordinates: "41.041994, 29.009049"
mapMobileCenterCoordinates: "41.041994, 29.009049"

# Venue Block
venueBlockTitle: "Konferans alanı"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Bahcesehir Konferans Merkezi"
venueFeatures: ["4 adet konferans salonu", "Sandbox alanı", "Şehrin merkezinde, kolay ulaşım imkanı"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Naber?"
twitterHashTag: "wtmistanbul"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizatörler"
partnersTitle: "Sponsorlar"
partnersC4sponsorsButton: "Sponsor Ol"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdgistanbul.us7.list-manage.com/subscribe/post?u=850f58b0963bc8227e3448ce6&amp;id=db62e82145"
subscribeInfo: "Registration will be open around end of February. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Kayıt Ol"
ticketsInfo: ""
ticketsOffers:
 -
  name: "Bedava Bilet"
  buyButtonLink: "http://wtmistanbul15.eventbrite.com"
  buyButtonText: "Kayıt Ol"
  additionalInfo: "Konferansa katılabilmek için kayıt olmalısınız."
  validFrom: ""
  validThrough: ""
 -
  name: "Startup Launch"
  buyButtonLink: "https://docs.google.com/forms/d/1Gt13d2GbSkFWcqV4bk1g_MbE17AvZVM5V5oHKH5wFd4/viewform?usp=send_form"
  buyButtonText: "Şimdi Başvur"
  additionalInfo: "Sahneye çıkma, fikirlerini VCler ile paylaşma ve networking partisine katılma imkanı."
  validFrom: ""
  validThrough: ""

# Footer
socialLinks:
 - {link: "https://plus.googleapis.com/communities/108925709024625495301", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=wtmistanbul", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/Women-Techmakers-Istanbul/671948679589644", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Bağlantılar"
  links:
   - {link: "http://www.gdgistanbul.com", text: "GDG Istanbul"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "İletişim"
  links:
   - {link: "mailto:wtm@gdgistanbul.com", text: "wtm@gdgistanbul.com"}
 -
  title: "SSS"
  links:
   - {permalink: "/cod/", text: "Adap Kuralı"}

# Blog
blogTitle: "Son haberler"
blogCommentsEnabled: true
discusShortName: "wtmistanbul"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "Hakkımızda"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Yol tarifi alın"
findWayDistance: "Uzaklık"
findWayDriving: "ARABAYLA"
findWayWalking: "YÜRÜYEREK"
findWayBicycling: "BİSİKLET"
findWayTransit: "OTOBÜS"
findWayFindFlight: "Uçak Bul"
logisticsMapCenterCoordinates: "41.041994, 29.009049"
logisticsMapMobileCenterCoordinates: "41.041994, 29.009049"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Istanbul'u keşfet"
directionDetailsCards:
 - {title: "Havaalanından", information: 'Havaalanı toplu taşıma ile kolay erişilen bir konumda. Metroya binebileceğiniz gibi HAVATAŞ otobüslerine de binebilirsiniz. Daha fazla bilgiyi <a href="http://www.ataturkairport.com/en-EN/Transportation/pages/airporttrasnportation.aspx">havaalanı internet sitesinde</a> bulabilirsiniz.'}
 - {title: "Toplu Taşıma", information: 'Metroyu kullanabileceğiniz gibi HAVATAŞ otobüslerini de bulabilirsiniz. İstanbul içerisinde toplu taşıma yol tarifi almak için bu uygulamayı tavsiye ediyoruz. <a href="http://www.trafi.com.tr/">Trafi App</a>'}
 - {title: "Oteller", information: 'Oteller hakkında bilgi daha sonra verilecektir.'}

# Hackathon
hackathonTitle: "Startup Launch"
enableHackathon: false

# Hackathon About Block
hackathonRows:
 - {details: "Girişimciler ve girşimci adayları, WTM İstanbul'da yatırımcılarla bir araya geliyor! <br/><br/>Katılımılar önce bir saatlik bir asansör konuşması workshopına katılacaklar sonrasında sahnede iş fikirlerini yatırımcılara sunacaklar.<br/>Etkinlikte sürprizlerimiz de olacak.<br/>Neden katılmalısın?<ul><li>Başarılı asansör konuşması workshopına katıl</li><li>Asansör konuşması pratiği yap</li><li>Sahne senin, iş fikrini yatırımcılara sunma imkanı</li><li>Diğer girişimcilerle tanışma imkanı</li></ul>"}
 - {title: "Ödüller", details: "Ayrıca IBM'den en iyi pitch sunumu yapanlara hediyemiz var!<br/>1. gelen kişi veya ekibe 1 yıl<br/>2. ekibe 6 ay<br/>3. ekibe de 3 ay Bluemix geliştirme platformu hediye!"}
 - {title: "Program", details: "Nasıl etkili asansör konuşması yapılır eğitimi (1 saat)<br/>Girşimcilerin sunumları - her biri 2 dk. (1 saat)<br/>Juri geri bildirimleri (1 saat)<br/>Networking (1 saat)"}
 - {title: "<a href='https://docs.google.com/forms/d/1Gt13d2GbSkFWcqV4bk1g_MbE17AvZVM5V5oHKH5wFd4/viewform?usp=send_form'>Şimdi Başvur</a>"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Jüri"

# Hackathon Prizes Block
prizesTitle: "Ödüller"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Istanbul"
hackathonAddressLocalityRegion: "Istanbul"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Turkey"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "Google Maps ile aç"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
