# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Women Techmakers Tbilisi 2015"
email: "wtm@gdgistanbul.com"
description: "Women Techmakers is a set of event about Women in technology"
baseurl: ""
url: "http://womentechmakers.ge/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-58630743-1"
googleAnalyticsSiteUrl: "womentechmakers.ge"
siteVerification: "J78BVBOHc0PWM6qbrydtmvG1KjsM5HFF4JUSzcuoqCw"

# Organizer Info
organizerName: "GDG Women Tbilisi"
organizerAlternateName: "Google Developer Group Tbilisi"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "wtm@gdgistanbul.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.gdgistanbul.com/"

# Head
metaKeywords: "wtm, women, womentechmakers, event, gdg, google, programming, android, chrome, developers, Tbilisi"
twitterAccount: "@wtmtbilisi"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/16AI23TnSQFg5yCqOIXeCj1hSlQvw1ihtx0XenZKfflk/viewform?usp=send_form"
c4sponsorsUrl: "https://docs.google.com/a/gdgistanbul.com/file/d/0B5Ewb5NwqbwIY0tvVTl2U2VjZkU/edit?usp=drive_web"


# Navigation
navigationLinks:
 - {permalink: "/", text: "მთავარი"}
 #- {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "პროგრამა"}
 - {permalink: "/speakers/", text: "სპიკერები"}
 - {permalink: "/#partners", text: "პარტნიორები"}
 #- {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "მდებარეობა"}
 #- {permalink: "/startup/", text: "Startup Launch"}
 - {permalink: "https://www.youtube.com/watch?v=UBIPRliSFVk", text: "WTMTbilisi'14"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/15BrehqDMIW4y972f-i55DkYLyk_Ke1-6mI27b7f7yiE/viewform", text: "რეგისტრაცია"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/15BrehqDMIW4y972f-i55DkYLyk_Ke1-6mI27b7f7yiE/viewform", text: "რეგისტრაცია"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "WTM თბილისი 2015"
eventDate: "29 მარტი, 2015"
typeoutTextValues: '"Women", "Techmakers", "Tbilisi"'
typeoutFallback: "Season"
heroButtons:
 - {permalink: "/schedule/", text: "პროგრამა"}
 - {link: "https://docs.google.com/forms/d/15BrehqDMIW4y972f-i55DkYLyk_Ke1-6mI27b7f7yiE/viewform", text: "რეგისტრაცია"}

# About Block
aboutTitle: "Women Techmakers თბილისი"
aboutBlock:
 - {title: "პანელი", image: "conference.jpg", text: "STEM პროფესიებში ქალების ჩართულობის წახალისება, წარმატებული მაგალითების ჩვენების საფუძველზე" }
 - {title: "ტექსაუბრები", image: "workshop.jpg", text: "საინტერესო გამომსვლელები სასარგებლო თემებზე" }
 - {title: "codelab", image: "hackathon.jpg", text: "მონაწილეები შეისწავლიან კონკრეტულ ტექნოლოგიას, მენტორის უშუალო დახმარებით კი შეძლებენ რეალური შედეგის მიღებას" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "დამსწრე", detail: "განურჩევლად სქესისა"}
 - {count: "12", specialCharacter: "+", info: "სპიკერი", detail: "ადგილობრივი და უცხოელი პროფესიონალები"}
 - {count: "6", specialCharacter: "+", info: "საათი", detail: "ტექნოლოგიური საუბრები, სადისკუსიო პანელი, Codelab"}

# Latest News Block
latestNewsTitle: "Son haberler"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 5
rockstarSpeakersTitle: "ქალი სპიკერები"
rockstarSpeakersButtonText: "ყველა სპიკერი"

# Location Block
locationBlockTitle: "ადგილი"
eventLocationName: "კახა ბენდუქიძის საუნივერსიტეტო კამპუსი"
eventLocationLink: "https://www.google.ge/maps/place/Dighomi+University+Campus/@41.8066109,44.7692284,17z/"
eventStreetAddress: "დავით აღმაშენებლის ხეივანი #240"
eventAddressLocality: "თბილისი"
eventAddressLocalityRegion: ""
eventPostalCode: ""
eventAddressCountry: "საქართველო"
eventStartTime: "2015-03-29T12:00"
eventDoorTime: "12:00"
eventEndTime: "2015-03-29T18:00"
eventPlaceCoordinates: "41.8066109,44.7692284"
mapCenterCoordinates: "41.806331,44.7665784"
mapMobileCenterCoordinates: "41.8066109,44.7692284"

# Venue Block
venueBlockTitle: "Konferans alanı"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Bahcesehir Konferans Merkezi"
venueFeatures: ["4 adet konferans salonu", "Sandbox alanı", "Şehrin merkezinde, kolay ulaşım imkanı"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "რა ხდება?"
twitterHashTag: "wtmtbilisi"
twitterFeed: ""

# Partners Block
organizersTitle: "ორგანიზატორები"
partnersTitle: "პარტნიორები"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdgistanbul.us7.list-manage.com/subscribe/post?u=850f58b0963bc8227e3448ce6&amp;id=db62e82145"
subscribeInfo: "Registration will be open around end of February. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "რეგისტრაცია"
ticketsInfo: ""
ticketsOffers:
 -
  name: "Ücretsiz Bilet"
  buyButtonLink: "http://wtmistanbul15.eventbrite.com"
  buyButtonText: "რეგისტრაცია"
  additionalInfo: "Konferansa katılabilmek için kayıt olmalısınız."
  validFrom: ""
  validThrough: ""
 # -
 #  name: "Startup Launch"
 #  buyButtonLink: "https://docs.google.com/forms/d/1Gt13d2GbSkFWcqV4bk1g_MbE17AvZVM5V5oHKH5wFd4/viewform?usp=send_form"
 #  buyButtonText: "Şimdi Başvur"
 #  additionalInfo: "Sahneye çıkma, fikirlerini VCler ile paylaşma ve networking partisine katılma imkanı."
 #  validFrom: ""
 #  validThrough: ""

# Footer
# Footer
socialLinks:
 - {link: "https://plus.google.com/u/0/106672659252619762166", icon: "google-plus"}
 - {link: "https://www.facebook.com/gdgtbilisi", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com/groups/chapter/1066726592619762166/", text: "GDG Tbilisi Group"}
   - {link: "gdgtbilisi.blogspot.com", text: "GDG Tbilisi Blog"}
   - {link: "https://developers.google.com/", text: "Google Developers"}
 -
  title: "Contact"
  links:
   - {link: "mailto:nino.nanitashvili@gmail.com", text: "nino.nanitashvili@gmail.com"}

# Blog
blogTitle: "Son haberler"
blogCommentsEnabled: true
discusShortName: "wtmistanbul"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Hakkımızda"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "როგორ მოვიდე?"
findWayDistance: "მანძილი"
findWayDriving: "მანქანით"
findWayWalking: "ფეხით"
logisticsMapCenterCoordinates: "41.8066109,44.7692284"
logisticsMapMobileCenterCoordinates: "41.8066109,44.7692284"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "ტრანსპორტის დეტალები"
directionDetailsCards:
 - {title: "მიკროავტობუსი", information: '<strong>44</strong> - ჭავჭავაძის გამზირი > ზაჰესი; <strong>51</strong> - ქავთარაძის ქუჩა > თბილისი მოლი; <strong>87</strong> - მეტროსადგური დიდუბე > თბილისი მოლი; <strong>116</strong> - გლდანის VII-VIII მ/რ > თბილისი მოლი; <strong>117</strong> - ვაზისუბანი > თბილისი მოლი;'}
 - {title: "ავტობუსი", information: '<strong>121</strong> - მეტროსადგური დიდუბე > ზაჰესი; <strong>84</strong> - სადგურის მოედანი > აღმაშენებლის ხეივანი; <strong>38</strong> - მეტრო დიდუბე > დიღმის საუნივერსიტეტო კამპუსი;'}

# Hackathon
hackathonTitle: "Startup Launch"
enableHackathon: false

# Hackathon About Block
hackathonRows:
 - {details: "Girişimciler ve girşimci adayları, WTM İstanbul'da yatırımcılarla bir araya geliyor! <br/><br/>Katılımılar önce bir saatlik bir asansör konuşması workshopına katılacaklar sonrasında sahnede iş fikirlerini yatırımcılara sunacaklar.<br/>Etkinlikte sürprizlerimiz de olacak.<br/>Neden katılmalısın?<ul><li>Başarılı asansör konuşması workshopına katıl</li><li>Asansör konuşması pratiği yap</li><li>Sahne senin, iş fikrini yatırımcılara sunma imkanı</li><li>Diğer girişimcilerle tanışma imkanı</li></ul>"}
 - {title: "Ödüller", details: "Ayrıca IBM'den en iyi pitch sunumu yapanlara hediyemiz var!<br/>1. gelen kişi veya ekibe 1 yıl<br/>2. ekibe 6 ay<br/>3. ekibe de 3 ay Bluemix geliştirme platformu hediye!"}
 - {title: "Program", details: "Nasıl etkili asansör konuşması yapılır eğitimi (1 saat)<br/>Girşimcilerin sunumları - her biri 2 dk. (1 saat)<br/>Juri geri bildirimleri (1 saat)<br/>Networking (1 saat)"}
 - {title: "<a href='https://docs.google.com/forms/d/1Gt13d2GbSkFWcqV4bk1g_MbE17AvZVM5V5oHKH5wFd4/viewform?usp=send_form'>Şimdi Başvur</a>"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Jüri"
instructorsTitle: "Startup Sunum Eğitmenleri"

# Hackathon Prizes Block
prizesTitle: "Ödüller"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Tbilisi"
hackathonAddressLocalityRegion: "Tbilisi"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Georgia"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "Google Maps-ზე ნახვა"
hackathonPlaceCoordinates: "41.8066109,44.7692284"
hackathonMapCenterCoordinates: "41.8066109,44.7692284"
hackathonMapMobileCenterCoordinates: "41.8066109,44.7692284"
